{"name": "test_get_pro_intent", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\workspace\\\\kuaishang_auto\\\\testdata\\\\apidata\\\\intent\\\\dermatology\\\\dermatology_test_data_3995'", "trace": "self = <test_get_intent.TestIntent object at 0x000001D355C6B4A8>\n\n    @pytest.mark.api_intention_test\n    @allure.feature(\"测试环境通用意图识别\")\n    def test_get_pro_intent(self):\n        # 意图测试\n        GetRequests().get_request(\"http://192.168.1.79:8900/intention/v2/skin\", \"GET\", \"skin_intent\",\n                                  \"intent\\\\dermatology\\\\线上target.txt\",\n                                  \"intent\\\\dermatology\\\\dermatology_test_data_3995\", [\"sentence\"], \"label\",\n                                  \"dermatology_intention_test_result.xls\",\n>                                 \"dermatology_intention_target_test_result.xls\")\n\napi\\test_get_intent.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\api\\get_requests.py:166: in get_request\n    test_data = ChangeDataType.csv_to_dict(rootPath + \"\\\\testdata\\\\apidata\\\\\" + test_data_file)\n..\\common\\change_data_type.py:85: in csv_to_dict\n    test_data = pandas.read_csv(file, encoding=\"utf-8\")\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:676: in parser_f\n    return _read(filepath_or_buffer, kwds)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:448: in _read\n    parser = TextFileReader(fp_or_buf, **kwds)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:880: in __init__\n    self._make_engine(self.engine)\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:1114: in _make_engine\n    self._engine = CParserWrapper(self.f, **self.options)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pandas.io.parsers.CParserWrapper object at 0x000001D355C6B7B8>\nsrc = 'D:\\\\workspace\\\\kuaishang_auto\\\\testdata\\\\apidata\\\\intent\\\\dermatology\\\\dermatology_test_data_3995'\nkwds = {'comment': None, 'compression': None, 'converters': {}, 'decimal': '.', ...}\nencoding = 'utf-8'\n\n    def __init__(self, src, **kwds):\n        self.kwds = kwds\n        kwds = kwds.copy()\n    \n        ParserBase.__init__(self, kwds)\n    \n        encoding = kwds.get(\"encoding\")\n    \n        if kwds.get(\"compression\") is None and encoding:\n            if isinstance(src, str):\n>               src = open(src, \"rb\")\nE               FileNotFoundError: [Errno 2] No such file or directory: 'D:\\\\workspace\\\\kuaishang_auto\\\\testdata\\\\apidata\\\\intent\\\\dermatology\\\\dermatology_test_data_3995'\n\nE:\\Python3.7.3\\lib\\site-packages\\pandas\\io\\parsers.py:1874: FileNotFoundError"}, "start": 1592465894434, "stop": 1592465894435, "uuid": "3432d50d-bc05-4c14-9c5a-34c675320a9a", "historyId": "5577602bedd8563b8ebaf88513cfdf02", "testCaseId": "49fe48d551064aad013d744258a73f22", "fullName": "pytest.api.test_get_intent.TestIntent#test_get_pro_intent", "labels": [{"name": "feature", "value": "测试环境通用意图识别"}, {"name": "tag", "value": "api_intention_test"}, {"name": "parentSuite", "value": "pytest.api"}, {"name": "suite", "value": "test_get_intent"}, {"name": "subSuite", "value": "TestIntent"}, {"name": "host", "value": "WIN-OQ20V7UABJF"}, {"name": "thread", "value": "23604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.api.test_get_intent"}]}